U_2004

diff --git a/.github/workflows/Gencsv.yml b/.github/workflows/Gencsv.yml
--- a/.github/workflows/Gencsv.yml
+++ b/.github/workflows/Gencsv.yml
@@ -1,4 +1,4 @@
-name: Gen Gold CSV
+name: Gen stocks csv
 
 on:
   workflow_dispatch:
@@ -32,20 +32,20 @@ jobs:
           pwd
           ls -la
           ls -la Allcsv || true
-          test -f Gold.csv && echo "Gold.csv exists" || (echo "Gold.csv missing" && exit 1)
+          test -f stocks.csv && echo "stocks.csv exists" || (echo "stocks.csv missing" && exit 1)
 
-      - name: Commit and push Gold.csv
+      - name: Commit and push stocks.csv
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
-          git add Gold.csv
+          git add stocks.csv
 
           if git diff --cached --quiet; then
             echo "No changes to commit"
             exit 0
           fi
 
-          git commit -m "Update Gold.csv"
+          git commit -m "Update stocks.csv"
           git pull --rebase origin main
           git push origin main
